#!/bin/zsh

cd "${0:A:h}"

PROFILE="--profile"

# TEST="examples/verilog/stall.v"
# TEST="test/verilog/pos/tr-submodule-01.v"
TEST="test/verilog/pos/tr-test-1.v"
# TEST="test/verilog/neg/neg-test-2-v0.v"
# TEST="benchmarks/472-mips-pipelined/mips_pipeline.v"
# TEST="benchmarks/crypto_cores/sha_core/trunk/rtl/sha256_stub_3.v"
# TEST="benchmarks/yarvi/shared/yarvi.v"
# TEST="benchmarks/fpu/verilog/fpu.v"

TEST_DIR="${TEST:h}"
TEST_NAME="${TEST:t:r}"

TEST_FILE="${TEST_DIR}/${TEST_NAME}.v"
TEST_ANNOT="${TEST_DIR}/annot-${TEST_NAME}.json"
# TEST_ANNOT="${TEST_DIR}/annot-${TEST_NAME}_fixed.json"

./iodine --build ${PROFILE} && \
	./iodine ${PROFILE} "${TEST_FILE}" "${TEST_ANNOT}" --trace
