#!/bin/zsh

cd "${0:A:h}"

# PROFILE="--profile"

TEST="test/verilog/pos/tr-test-2.v"
TEST_DIR="${TEST:h}"
TEST_NAME="${TEST:t:r}"

TEST_FILE="${TEST_DIR}/${TEST_NAME}.v"
TEST_ANNOT="${TEST_DIR}/annot-${TEST_NAME}.json"

./iodine --build ${PROFILE} && \
	./iodine ${PROFILE} "${TEST_FILE}" "${TEST_ANNOT}" --trace
