name:                iodine
version:             0.1.0.0
github:              "gokhankici/iodine"
license:             MIT
author:              "Rami Gokhan Kici"
maintainer:          "gokhankici@gmail.com"
copyright:           "2018 Rami Gokhan Kici"

extra-source-files:
- README.md

synopsis:            Generates the transition relation & verification conditions from a Verilog IR
category:            Hardware Verification

description:         Please see the README on Github at <https://github.com/gokhankici/iodine#readme>

custom-setup:
  dependencies:
  - base
  - Cabal

ghc-options:
- -O2
- -flate-specialise
- -fspecialise-aggressively
- -Werror
- -fdefer-type-errors
- -fwarn-incomplete-patterns
- -fwarn-incomplete-record-updates
- -fwarn-incomplete-uni-patterns
- -fwarn-missing-signatures
- -fwarn-name-shadowing
- -fwarn-orphans
- -fwarn-overlapping-patterns
- -fwarn-redundant-constraints
- -fwarn-tabs
- -fwarn-unused-binds
- -fwarn-unused-imports
- -fwarn-unused-matches

default-extensions:
- ConstraintKinds
- DataKinds
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GeneralizedNewtypeDeriving
- LambdaCase
- MultiParamTypeClasses
- PolyKinds
- RankNTypes
- ScopedTypeVariables
- TypeApplications
- TypeFamilies
- TypeOperators
- UndecidableInstances

dependencies:
- base >= 4.7 && < 5
- aeson
- bytestring
- cmdargs
- containers
- deepseq
- directory
- dlist
- fgl
- filepath
- fused-effects
- fused-effects-lens
- hashable
- hspec
- hspec-core
- lens
- liquid-fixpoint
- megaparsec
- mtl
- pretty
- process
- text
- transformers
- unordered-containers
- vector

library:
  source-dirs:     src

executables:
  iodine:
    main:          Main.hs
    source-dirs:   app
    ghc-options:
    - -O2
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - iodine
  prolog-pretty:
    main:          Main.hs
    source-dirs:   prolog-pretty-app
    ghc-options:
    - -O2
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - iodine
  iodine-debug:
    main:          Main.hs
    source-dirs:   dbg
    ghc-options:
    - -O2
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - iodine

tests:
  iodine-test:
    main:          Test.hs
    source-dirs:   test
    ghc-options:
    - -O2
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - iodine
